version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/config-api"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
      semver-major-days: 14
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/satosa/tests"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
      semver-major-days: 14
    groups:
      python-test-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/config-api"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
      semver-major-days: 14

  - package-ecosystem: "docker"
    directory: "/satosa"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
      semver-major-days: 14

  - package-ecosystem: "docker"
    directory: "/nginx"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
      semver-major-days: 14

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
      semver-major-days: 14
