version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/config-api"
    schedule:
      interval: "weekly"
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/satosa/tests"
    schedule:
      interval: "weekly"
    groups:
      python-test-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/config-api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/satosa"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/nginx"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
