services:
  satosa:
    image: pa-sso-proxy-satosa:local
    build:
      context: ./satosa

  config-api:
    image: pa-sso-proxy-config-api:local
    build:
      context: ./config-api
    volumes:
      - ./.git:/app/.git:ro
